### ISSUE TITLE
Tests to carry out!

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/KSS#60]
- [x] #2 saves should be deleteable by admins, with confirmation prompt before carrying out the deletion
  - Note: Not part of `proto1.5`
- [x] #52 time remaining should show up (note: I don't expect this to actually be working)
- [x] #59 next user should be correct now
- [ ] #48 users with spaces in their name should be accessible now (at least in their user display)
  - NOTE: THIS IS NOT FIXED AT ALL EVEN IF THIS WORKS! All user access needs to go through unescape() if this works. Needs to also be tested with users with `&` in their names, or `&amp;` in their names.
- [x] Users list should be ordered better (see [this commit](https://github.com/Guard13007/KSS/commit/e54e4ba4d4cb2e41fb7d1465ddb3c0a2c6f0551a))
- [x] #46 footer should have been added with a link to the source and issues

**Comment by TangentFoxy** [comment]
#52 is not fixed, but I have an idea for how to fix it. (Essentially, a day's seconds - today's seconds = time remaining in seconds, process from there)

**Comment by TangentFoxy** [comment]
That took far too much out of me...should've been easier. This is what I get for being up late. (I'm talking about #52)

**Comment by TangentFoxy** [comment]
#48 is probably fixed as long as I don't allow usernames to end with a space. I'm going to close _this_ issue, but not it. It will receive a note about the potential problems for later investigation.
