### ISSUE TITLE
Broad amazing future concepts of awesomeness!

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/KSS#64]
- [ ] Form for submitting bug reports.
- [ ] Form for submitting modpack bug reports.
- [ ] Notification system for users.
- [ ] Email notification system for users? (Mailgun!) See #78
- [ ] Recaptcha no-captcha thingie on registration forms? See #80
- [ ] Mod pack listing / tools / whatever. See #65
